### ISSUE TITLE
Update to NGRX 14

### ISSUE THREAD

**Issue by PointSingularity** [timdeschryver/ngrx-immer#16]
Thanks for the great library!

I was wondering if there were plans for upgrading to NGRX version 14?
I saw it was already updated in the 'package.json' but it still isn't published.

**Comment by timdeschryver** [comment]
The current version should work with Ngrx >= 13, that's why I didn't release a new version.
Did you encounter anything that doesn't work?

**Comment by PointSingularity** [comment]
> The current version should work with Ngrx >= 13, that's why I didn't release a new version. Did you encounter anything that doesn't work?

Just went through upgrading my App to Angular/NGRX 14  and everything still works 😁
I was just looking through different dependencies I had in the project, and looking for version mismatches.

I'll go ahead and close it, thank you.

**Comment by timdeschryver** [comment]
Thanks for the quick reply, feel free to open an issue if there are any problems.
