### ISSUE TITLE
Add immer implementations of @ngrx/signals 

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/ngrx-immer#21]
Coming from https://github.com/ngrx/platform/issues/3998

**Comment by xianshenglu** [comment]
@timdeschryver  Hi, any update for this feature?

**Comment by timdeschryver** [comment]
@xianshenglu this needs to be implemented 😅
If you want to contribute, feel free to drop your a comment here and it will get assigned to you

**Comment by timdeschryver** [comment]
@rainerhahnekamp I'm assigning this to you.
I've added the "infrastructure" so you can focus on the "good stuff".
Feel free to ping me if you need help.

**Comment by rainerhahnekamp** [comment]
Alright, thanks Tim and I'll contact you if I have any questions or just push the PR once it is ready

**Comment by rainerhahnekamp** [comment]
Quick update here. PR should be ready by tomorrow. Should give us enough time for a proper review and improvements before Marko's talk at ng-conf.

**Comment by timdeschryver** [comment]
Thanks @rainerhahnekamp

**Comment by rainerhahnekamp** [comment]
@timdeschryver, there is a little bit of a problem with the testing. To verify that only the patched Signals emit, I need to use `TestBed.flushEffects()`.

I'll have to add Jest in that case. I prefer Jasmine, but that might be an overkill.

**Comment by timdeschryver** [comment]
> @timdeschryver, there is a little bit of a problem with the testing. To verify that only the patched Signals emit, I need to use `TestBed.flushEffects()`.
> 
> I'll have to add Jest in that case. I prefer Jasmine, but that might be an overkill.

That's fine, feel free to use jest for this.

**Comment by rainerhahnekamp** [comment]
https://github.com/timdeschryver/ngrx-immer/pull/24

**Comment by timdeschryver** [comment]
Closed by #24
