### ISSUE TITLE
Any plan to update the library to adapt to ngrx 18?

### ISSUE THREAD

**Issue by ilara-tws** [timdeschryver/ngrx-immer#28]
We are using the version 18 of ngrx and we have realised that this library is not yet adapted to this version.
Is there any plan to update it?
Thanks

**Comment by timdeschryver** [comment]
I was assuming that there weren't any problems, if there are then we'll update it.
Do you want to create a PR with the update?

**Comment by adam42389** [comment]
I would second this please. The package appears to work for v18, however we had to use --force flag to install it which isn't ideal.
Great library and thanks for maintaining.
