### ISSUE TITLE
source code is not up to date?

### ISSUE THREAD

**Issue by xianshenglu** [timdeschryver/ngrx-immer#5]
Hi, I really appreciate the lib you create~~

However, as the title said, it seems the source code isn't consistent with the version published in the npm? I guess you forget pushing?

Anyway, thanks for your creation~

**Comment by timdeschryver** [comment]
Yikes, I completely forgot that the release step is commented out in the CI...
I'll try to fix this later today.
Thanks!

**Comment by timdeschryver** [comment]
V1.0.1 is released, which is the latest version.
