### ISSUE TITLE
Considering release a new version with license file?

### ISSUE THREAD

**Issue by xianshenglu** [timdeschryver/ngrx-immer#6]
Hi, I see you add a license file because of this issue https://github.com/timdeschryver/ngrx-immer/issues/2. 

That's really great! 

But when I'm trying to install the latest version(v0.0.5) in npm, I found the final package missing the license file. So, could we release a new version to include the license file?

Anyway, thanks very much~

**Comment by timdeschryver** [comment]
V1.0.1 contains the LICENSE.
