### ISSUE TITLE
The Selector of ImmerComponentStore isn't working similarly as Component Store

### ISSUE THREAD

**Issue by nhvu95** [timdeschryver/ngrx-immer#9]
https://stackblitz.com/edit/angular-ivy-ebkzxz?file=src/app/non-immer/non-immer.component.ts
Please follow the demo above. and please check the console log.

**Comment by timdeschryver** [comment]
You're  right, but this is by design.
[Immer](https://immerjs.github.io/immer/) creates an immutable state, thus you can't simply update it.
You're only allowed to update state in the update methods.
